services:
  prometheus:
    image: prom/prometheus:latest
    restart: always
    command: [
      "--config.file=/etc/prometheus/prometheus.yml",
      "--storage.tsdb.path=/prometheus",
      "--storage.tsdb.retention.time=30d",
      "--web.console.libraries=/usr/share/prometheus/console_libraries",
      "--web.console.templates=/usr/share/prometheus/consoles",
      "--web.enable-lifecycle"
    ]
    network_mode: "host"
    expose:
      - "9090"
    volumes:
      - prometheus-data:/prometheus
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:latest
    restart: always
    network_mode: "host"
    expose:
      - "3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./config/grafana.ini:/etc/grafana/grafana.ini:ro
volumes:
  prometheus-data:
  grafana-data:
